### ISSUE TITLE
L2TP

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#10]
В RFRemix в Network Manager есть возможность для настройки L2TP VPN, что бывает полезно при подключении к некоторым российским провайдерам интернета. Как это можно сделать в других дистрибутивах, например в обычной Fedora?

**Comment by nexfwall** [comment]
Поставить соответствующий [пакет](https://koji.fedoraproject.org/koji/packageinfo?packageID=15089) с плагином?
