### ISSUE TITLE
Аппаратное видеоускорение в Firefox

### ISSUE THREAD

**Issue by shdwchn10** [RussianFedora/FAQ#100]
Страница, на которой присутствует ошибка: 
https://russianfedora.github.io/FAQ/using-applications.html#hwaccel-firefox

Гайд из FAQ не учитывает существование `media.rdd-process.enabled` и этого бага: https://bugzilla.mozilla.org/show_bug.cgi?id=1683808

`media.rdd-process.enabled` должен быть установлен в false, иначе декодирование через VA-API не будет работать. Однако, переключение этого параметра в false, сказывается на безопасности браузера.

**Comment by xvitaly** [comment]
Давно этот баг появился? У меня работало VA-API на Intel без каких-либо проблем, как только эту поддержку добавили патчами в пакет Fedora.
