### ISSUE TITLE
Дополнить инструкцию по настройке firewalld для wireguard

### ISSUE THREAD

**Issue by LLlalun** [RussianFedora/FAQ#101]
Страница, на которой присутствует ошибка: 
https://www.easycoding.org/2019/02/28/podnimaem-wireguard-server-na-fedora.html

Подробно опишите её:
С Fedora 33 настроен сервер wireguard согласно инструкции выше. В системе все настройки по умолчанию. Никаких дополнительных настроек firewalld не выполнялось. VPN работал, доступ с телефона через него в интернет так же работал.

После обновления на Fedora 35 подключение к VPN работало, но попытка пинговать ip хоста (не vpn) - packet filtered. Попытка подключиться к интернет - нет доступа. В логах обнаружилось такое:
```jourrnalctl
ноя 22 14:37:24 server kernel: "filter_FWD_FedoraServer_REJECT: "IN=wg0 OUT=eno0 MAC= SRC=ip_устройства DST=64.233.161.198 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=54488 PROTO=TCP SPT=49473 DPT=443 WINDOW=65535 RES=0x00 SYN URGP=0
ноя 22 14:38:38 server kernel: "filter_FWD_FedoraServer_REJECT: "IN=wg0 OUT=eno0 MAC= SRC=ip_устройства  DST=74.125.131.95 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=764 PROTO=TCP SPT=40598 DPT=443 WINDOW=65535 RES=0x00 SYN URGP=0
ноя 22 14:38:47 server kernel: "filter_FWD_FedoraServer_REJECT: "IN=wg0 OUT=eno0 MAC= SRC=ip_устройства DST=ip_роутера LEN=62 TOS=0x00 PREC=0x00 TTL=63 ID=61650 PROTO=UDP SPT=43482 DPT=53 LEN=42
```
В чате подсказали, что обновился firewalld до версии 1.0.
На opennet нашёл [статью](https://www.opennet.ru/opennews/art.shtml?num=55537).
> Действие "default", указываемое в параметре "--set-target", теперь эквивалентно "reject", т.е. все пакеты, не подпадающие под определённые в зоне правила, по умолчанию будут блокироваться. Исключение сделано только для ICMP-пакетов, которые по-прежнему пропускаются. Для возвращения старого поведения для публично доступной зоны "trusted" можно использовать правила: 
   firewall-cmd --permanent --new-policy allowForward 
   firewall-cmd --permanent --policy allowForward --set-target ACCEPT
   firewall-cmd --permanent --policy allowForward --add-ingress-zone public
   firewall-cmd --permanent --policy allowForward --add-egress-zone trusted
   firewall-cmd --reload

Выполнил настройку со своими зонами (FedoraServer) - заработало.

Т.е. в инcтрукцию необходимо добавить дополнительные настройки для firewalld. **Возможно** есть лучше варианты, чем возвращение старого поведения для "default".

**Comment by xvitaly** [comment]
Маскарадинг на интерфейсе точно был включён? После обновления все настройки были сброшены, поэтому требовалась полная настройка с нуля.

**Comment by LLlalun** [comment]
Проверял, отображался, что включён.
Заново дополнительно не включал, только настройки выше.

**Comment by xvitaly** [comment]
>  Заново дополнительно не включал, только настройки выше.

WireGuard работает на стандартном порту?

**Comment by LLlalun** [comment]
да 27015
wireguard.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Wireguard Server</short>
  <description>Wireguard Server</description>
  <port port="27015" protocol="udp"/>
</service>
```

**Comment by xvitaly** [comment]
>  wireguard.xml

Теперь в состав FirewallD входит готовый конфиг для WireGuard с одноимённым названием, поэтому нужно либо [создавать оверрайд](https://russianfedora.github.io/FAQ/networking.html#firewalld-override) в `/etc/firewalld/services/wireguard.xml`, либо использовать другое имя для своего конфига.

**Comment by LLlalun** [comment]
> /etc/firewalld/services/wireguard.xml 

Именно там мой конфиг и лежит.
Порт настроил как в FAQ - 21075.

Дефолтный конфиг `/usr/lib/firewalld/services/wireguard.xml` отличается только портом:
```xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>WireGuard</short>
  <description>WireGuard is the simple, fast and modern VPN. The port needs to be open if a peer has this host explicitly configured as endpoint.</description>
  <port protocol="udp" port="51820"/>
</service>

```

**Comment by xvitaly** [comment]
> Только вот в интернет через VPN не пускало, пока не настроил allowForward.

Основной шлюз для VPN соединения был задан корректно?

**Comment by LLlalun** [comment]
> Основной шлюз для VPN соединения был задан корректно?

Да.
До обновления сервера успешно использовалось. После обновления - перестало. Пока не поправил политики firewalld.
Возможно потому что у firewalld оставлена и используется только зона по умолчанию (FedoraServer).

**Comment by xvitaly** [comment]
>  Возможно потому что у firewalld оставлена и используется только зона по умолчанию (FedoraServer).

Скорее всего. Предустановленные Fedora* зоны ужасно кривые, особенно для десктопа. Рекомендую попробовать `public`.

**Comment by Vascom** [comment]
Что-то у меня похожая проблема.
VPN работает, в интернет ходит, разные компы друг друга видят. Но не видна локалка за компом.
Раньше работало. Всё сделано по инструкции https://russianfedora.github.io/FAQ/networking.html#wireguard-lan
Что делать?

**Comment by xvitaly** [comment]
> Вот что нарыл: https://bugzilla.redhat.com/show_bug.cgi?id=2020974

Похоже, что модификация sysctl более не требуется. Если так, то это даже хорошо.

>  Помогает такая команда firewall-cmd --permanent --zone <zone> --add-forward

@LLlalun Просьба проверить будет ли работать этот способ.

**Comment by LLlalun** [comment]
Удалил политику из начала поста.
Настроил `firewall-cmd --permanent --zone <zone> --add-forward` - работает. 
Доступ в интернет есть и доступ в локальную сеть есть.

**Comment by Vascom** [comment]
Предлагаю принять это решение и дополнить им оба пункта FAQ.

**Comment by xvitaly** [comment]
>  Доступ в интернет есть и доступ в локальную сеть есть.

Благодарю. Обновим статью.

> Предлагаю принять это решение и дополнить им оба пункта FAQ.

Пришлёшь PR?

**Comment by xvitaly** [comment]
Статья обновлена, а равно как и FAQ. Благодарю за информацию об этом и тестирование.
