### ISSUE TITLE
make hmtl error 127

### ISSUE THREAD

**Issue by anidzelskiy** [RussianFedora/FAQ#11]
Выполняю инструкцию и получаю ошибку. Есть решение?

~/fedora-faq-ru> make html
                                      
/bin/sh: sphinx-build: команда не найдена
make: *** [Makefile:28: html] Ошибка 127

У меня cat /etc/os-release 
NAME=Fedora
VERSION="29 (Workstation Edition)"

**Comment by xvitaly** [comment]
> Выполняю инструкцию и получаю ошибку. Есть решение?

Необходимо повторно войти в систему после установки sphinx-doc пакета ибо он модифицирует переменную окружения $PATH.
