### ISSUE TITLE
Разница между командами dnf upgrade и dnf distro-sync

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#112]
Подробно опишите своё предложение:
В пункте 3.10 Как правильно обновлять систему? приведена команда для обновления sudo dnf upgrade --refresh
Но, помимо этой команды существует еще и команда dnf distro-sync. Из описания ясно, что последняя может производить как апгрейд, так и даунгрейд системы, приводя ее к некоторому актуальному состоянию. Однако не понятно в каких случаях лучше использовать первую команду, а в каких - вторую. И не удалит ли команда distro-sync установленные пользователем пакеты?

**Comment by xvitaly** [comment]
> Но, помимо этой команды существует еще и команда dnf distro-sync

Это команда синхронизации репозиториев с эталонным состоянием репозиториев. Использовать для обновления её не следует, т.к. повлечёт за собой откат и удаление любых пакетов обновлённых не из репозиториев, а например из Koji.

> И не удалит ли команда distro-sync установленные пользователем пакеты?

Отсутствующие в репозиториях не удалит, но сделает откат всех пакетов до версий из репозиториев, включая установленные вручную.
