### ISSUE TITLE
Пункт 3.31 FAQ Установка кодеков

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#113]
В пункте 3.11 FAQ приведена команда для установки кодеков sudo dnf groupupdate multimedia sound-and-video
Однако, во-первых, в выводе команды sudo dnf group list нет группы multimedia.
Во-вторых вроде бы более правильно писать dnf group upgrade 'Sound and Video'
В-третьих группы Sound and Video нет в числе установленных (но проверял на версии Fedora 35 и 36Beta с LXQT), так что возможно, следует выполнить команду dnf group install 'Sound and Video' ?

upd.
Зашел на сайт https://rpmfusion.org/ и в секции Multimedia post-install приведены такие команды:

The following command will install the complements multimedia packages needed by gstreamer enabled applications:
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

The following command will install the sound-and-video complement packages needed by some applications:
sudo dnf groupupdate sound-and-video

**Comment by xvitaly** [comment]
>  Однако, во-первых, в выводе команды sudo dnf group list нет группы multimedia.

Так и должно быть. В выводе `dnf group list` отображается user-friendly описание, а не её comps-id.

>  Во-вторых вроде бы более правильно писать dnf group upgrade 'Sound and Video'

Это всего лишь альтернативная форма написания, но из-за того, что имя требуется брать в кавычки из-за наличия пробелов, наиболее предпочтительным вариантов на мой взгляд является прямое наименование sound-and-video.

```
$ sudo dnf groupupdate multimedia sound-and-video
Last metadata expiration check: 0:01:34 ago on Tue 03 May 2022 09:58:37.
No match for group package "PackageKit-gstreamer-plugin"
No match for group package "k3b-extras-freeworld"
No match for group package "gstreamer1-plugin-openh264"
Dependencies resolved.
================================================================================================
 Package                       Arch       Version              Repository                  Size
================================================================================================
Installing group/module packages:
 pipewire-gstreamer            x86_64     0.3.51-1.fc35        updates                     59 k
 pipewire-utils                x86_64     0.3.51-1.fc35        updates                    330 k
 qt5-qtwebengine-freeworld     x86_64     5.15.8-2.fc35        rpmfusion-free-updates      44 M
Installing dependencies:
 libfreeaptx                   x86_64     0.1.1-2.fc35         rpmfusion-free              29 k
 pipewire-codec-aptx           x86_64     0.3.49-1.fc35        rpmfusion-free-updates      24 k
Installing Groups:
 Multimedia
 Sound and Video

Transaction Summary
================================================================================================
Install  5 Packages

Total download size: 45 M
Installed size: 132 M
Is this ok [y/N]: n
Operation aborted.
```

> В-третьих группы Sound and Video нет в числе установленных (но проверял на версии Fedora 35 и 36Beta с LXQT), так что возможно, следует выполнить команду dnf group install 'Sound and Video' ?

В Fedora группы не отображаются установленными, т.к. группа предоставляет собой просто XML-файл со списком пакетов, ей принадлежащих, а не мета-пакет, как в Ubuntu/Debian.

>  sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

Это просто косметическое скрытие сообщения dnf:

> No match for group package "PackageKit-gstreamer-plugin"

На реальную работу не влияет.
