### ISSUE TITLE
wayland kde nvidia liveCD

### ISSUE THREAD

**Issue by ssergey2018** [RussianFedora/FAQ#119]
Есть ли возможность запустить liveCD с kde и видеоадаптером nvidia? при запуске получаю зависшую систему. решений, как я понимаю два:
1) запустить сессию на Xorg, но не понятно как переключиться на него при старте с liveCD (нет возможности завершить текущий сеанс для переключения на Xorg)
2) Ставить серверный вариант и накатывать руками KDE с соответствующими драйверами и параметрами ядра
Есть возможность добавить инструкцию в FAQ для данной ситуации?
Благодарю за внимание

**Comment by xvitaly** [comment]
Ответ уже есть в FAQ: https://russianfedora.github.io/FAQ/tips-and-tricks.html#fedora-36-kde-nvidia
