### ISSUE TITLE
Fedora не загружается с новым ядром

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#12]
Есть компьютер. UEFI/GPT. На одном жестком диске установлены Windows 10, openSUSE Tumbleweed и Fedora 29. При загрузке компьютера выводится меню GRUB со списком всех трех ОС для загрузки. Само меню GRUB принадлежит openSUSE и меня это вполне устраивает. 

Вот только Fedora все время загружается с ядром 4.18 (судя по выводу команды uname -r), хотя она уже обновилась и в списке установленных присутствует версия 4.19.

Как заставить Fedora загружаться с новым ядром?
Пробовал в openSUSE команду 
`grub2-mkconfig -o /boot/efi/EFI/opensuse/grub.cfg`, 
а в Fedora 
`grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`, 
но это не помогло.

**Comment by digitalsimulator** [comment]
UPD. 
GRUB Fedora видит оба ее ядра и по умолчанию заружает новое, хотя он и не видит openSUSE. В любом случае признаю, что тема не имеет непосредственного отношения к самой Fedora, так что, возможно, ее стоит закрыть.

**Comment by xvitaly** [comment]
Вся проблема заключается в том, что в UEFI режиме каждый дистрибутив устанавливает собственную копию загрузчика GRUB в ESP раздел. Для Fedora это `/boot/efi/EFI/fedora`, openSUSE - `/boot/efi/EFI/opensuse`, Debian - `/boot/efi/EFI/debian` и т.д.

Эти загрузчики видят только свои собственные ядра.
