### ISSUE TITLE
Hibernation fedora 37

### ISSUE THREAD

**Issue by rodin-ia** [RussianFedora/FAQ#122]
При дефолтной установке 37+GNOME не работает выход из гибернации без параметра 
add_dracutmodules+=" resume "  в /etc/dracut.conf, возможно это стоить добавить в документацию.

**Comment by xvitaly** [comment]
В дефолтной установке Fedora начиная с версии 36 включен zram (сжатие памяти через виртуальный файл подкачки), поэтому гибернация в любом случае работать не будет без его отключения.

**Comment by rodin-ia** [comment]
Спасибо, в моей инсталиции были swap раздел и zram. При такой конфигурации, добавление параметра в dracut.conf и редактирование grub.conf поволило пользоваться гибернацией.
