### ISSUE TITLE
Команда package-cleanup отсутствует

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#13]
В "Большом FAQ по Fedora" дается следующая рекомендация:

> Удалить дубликаты и повреждённые пакеты можно так:
sudo package-cleanup --cleandupes --noscripts

Однако при вызове команды package-cleanup появляется сообщение:
-bash: package-cleanup: command not found

А при поиске этой команды с помощью dnf search package-cleanup появляется сообщение:
No matches found.
(Fedora 29)

**Comment by Vascom** [comment]
Она в пакете dnf-utils.
И не имеет опции --noscripts.

Надо обновить FAQ.
