### ISSUE TITLE
Opera browser

### ISSUE THREAD

**Issue by batollo** [RussianFedora/FAQ#19]
Установил opera-browser с официального сайта, но при dnf update приходит устаревшее "обновление" из репозитория RFR, как поступить в данном случае?

**Comment by Vascom** [comment]
Добавь в файл /etc/dnf/dnf.conf исключение:
`exclude=opera-browser`

**Comment by batollo** [comment]
Как исправить
![operup](https://user-images.githubusercontent.com/47214084/52055572-314e5b00-2579-11e9-98ec-f901d77000ee.png)

**Comment by batollo** [comment]
Чтобы не появлялось это сообщение?

**Comment by Vascom** [comment]
Я же написал как.
Вообще можешь отключить эту уведомлялку.

**Comment by batollo** [comment]
Добавил в файл /etc/dnf/dnf.conf исключение:
exclude=opera-stable, а не opera-browser, так сработало.
Благодарю, Добра!

**Comment by Vascom** [comment]
Как у тебябыло написано в исходном сообщении, так я и посоветовал :)

**Comment by batollo** [comment]
Вы правы!
