### ISSUE TITLE
Поддержка мультимедиа в Fedora

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#22]
Сейчас бегло посмотрел FAQ по Fedora и не нашел ответа (хотя может плохо искал).
Меня интересует какие кодеки и программы нужно установить для нормальной поддержки мультимедиа в Fedora. Я говорю о кодеках, чтобы можно было слушать музыку, смотреть видео на локальной системе или онлайн. Я не имею в виду программы типа vlc, audacity, mpv, avdemux и т.п. В Russian Fedora Remix поддержка мультимедиа присутствует "из коробки", но для обычной Fedora это актуальный вопрос.

Я смог настроить Fedora для основной работы с видео и звуком, но действовал бессистемно. А хотелось бы знать, какие пакеты устанавливать нужно, какие не обязательно, а какие будут избыточными. Ну и хорошо бы дополнить этой информацией FAQ.

**Comment by xvitaly** [comment]
> Меня интересует какие кодеки и программы нужно установить для нормальной поддержки мультимедиа в Fedora.

https://russianfedora.github.io/FAQ/package-manager.html#multimedia-codecs

> В Russian Fedora Remix поддержка мультимедиа присутствует "из коробки", но для обычной Fedora это актуальный вопрос.

Данная группа в RFRemix предустановлена.

**Comment by digitalsimulator** [comment]
> https://russianfedora.github.io/FAQ/package-manager.html#multimedia-codecs

> 
Понял. Я действительно плохо смотрел FAQ.
