### ISSUE TITLE
Отключение защиты Meltdown и Spectre

### ISSUE THREAD

**Issue by digitalsimulator** [RussianFedora/FAQ#23]
В FAQ по Fedora для отключения защиты Meltdown и Spectre предлагается передать ядру такие параметы: nopti (или pti=off), nospectre_v1, nospectre_v2, nospec_store_bypass_disable, и еще l1tf=off для отключения L1TF.

А что насчет параметра PR_SPEC_DISABLE_NOEXEC ? Вот здесь небольная заметка [https://habr.com/ru/company/1cloud/blog/442140/](url) Этот параметр тоже как будто предназначен для отключения защиты Spectre v4.

Еще предлагаю дополнить FAQ инструкцией куда и как добавлять эти параметры. Как я выяснил, их нужно добавить в файл /etc/default/grub, в строку GRUB_CMDLINE_LINUX
И затем нужно выполнить команду `grub2-mkconfig -o /boot/grub2/grub.cfg` Или правильнее будет выполнить `grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg` ? 

UPD. Я нашел куда и как писать эти параметры в FAQ, просто можно ссылку на них дать из радела про отключение Meltdown / Spectre.

**Comment by xvitaly** [comment]
> Этот параметр тоже как будто предназначен для отключения защиты Spectre v4.

Это не параметр ядра, а переменная окружения, которая может использоваться, чтобы отключать prctl для конкретного процесса.

> Еще предлагаю дополнить FAQ инструкцией куда и как добавлять эти параметры.

https://russianfedora.github.io/FAQ/administration.html#kernelpm-once
https://russianfedora.github.io/FAQ/administration.html#kernelpm-perm

> Или правильнее будет выполнить

https://russianfedora.github.io/FAQ/using-system.html#grub-rebuild
