### ISSUE TITLE
Обновился до rfremix 29, куда делась правая кнопка на тачскрине ноутбука, нажатие на правую кнопку не работает, теперь в файловом менеджере ни папку не создать, вообще неудобно работать

### ISSUE THREAD

**Issue by rettym** [RussianFedora/FAQ#30]

**Comment by xvitaly** [comment]
1. С RFRemix нужно [срочно переключиться](https://t.me/rfrnews/1273) на обычную Fedora.
2. Необходимо обновиться до Fedora 30 ибо баги предыдущих версий уже исправлять никто не будет.
