### ISSUE TITLE
Опечатка в п.3, раздела 9.27 ("Как перенести кэш браузера Firefox в tmpfs?" )

### ISSUE THREAD

**Issue by sk-it** [RussianFedora/FAQ#31]
Сейчас написано:

> 3. чтобы кэш очень сильно не разрастался, укажем в переменной browser.cache.
> disk.capacity максимальный размер в байтах, например 262144 (256 МБ);

Нужно написать:

> 3. чтобы кэш очень сильно не разрастался, укажем в переменной browser.cache.
> disk.capacity максимальный размер в **КИЛОбайтах**, например 262144 (256 МБ);

Чтобы я добавил еще к этому пункту: сведения о типе параметра **INTEGER**.

**Comment by xvitaly** [comment]
Исправлено. Спасибо.
