### ISSUE TITLE
Полезные сторонние репозитории для Fedora - 2

### ISSUE THREAD

**Issue by sotnikov123** [RussianFedora/FAQ#49]
Подробно опишите своё предложение:
https://www.easycoding.org/2017/03/24/poleznye-storonnie-repozitorii-dlya-fedora.html

В связи с тем, что VSCode всё равно используют и советуют репозиторий vscodium вместо официального:
1. на офсайте не добавлено skip_if_unavailable=True
2. активация репозитория через dnf
3. напоминание отключить телеметрию для паранойщиков

sudo bash -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc\nskip_if_unavailable=True" > /etc/yum.repos.d/vscode.repo'
sudo dnf config-manager --set-enabled code
отключаем телеметрию тут: 
ctrl+, -> Application -> Telemetry

**Comment by xvitaly** [comment]
Сделаем лучше - добавим реп сюда: https://github.com/RussianFedora/fedora-extra-repos

**Comment by xvitaly** [comment]
Добавил в статью:

```
sudo dnf config-manager --add-repo=https://github.com/RussianFedora/fedora-extra-repos/raw/master/code.repo
```
