### ISSUE TITLE
Ошибка в описании Firewalld

### ISSUE THREAD

**Issue by krepver** [RussianFedora/FAQ#5]
В описании сказано

> Firewalld не является надстройкой над iptables, как многие ошибочно считают. Firewalld - это полнофункциональный самодостаточный фронтенд над ядерным модулем netfilter.

Но это не так. Он им являлся до версии 0.6.0 (релиз в июне 2018), а теперь он надстройка над nftables (с возможностью переключиться обратно на iptables). Смотрим [конфиг](https://github.com/firewalld/firewalld/blob/master/config/firewalld.conf#L64).

А так же запись в [блоге](https://firewalld.org/2018/07/nftables-backend) и [release notes](https://firewalld.org/2018/07/firewalld-0-6-0-release).

> firewalld interacts with nftables directly through the nft binary. This is similar to how firewalld currently interacts with iptables and family. In a future release interaction with nftables will be further improved by using the newly minted libnftables.

**Comment by krepver** [comment]
Так на картинке с netfilter взаимодействует не сам firewalld, а бекенды (iptables или nft).

А вот указать, что именно служба iptables (у которой свой конфиг и правила) не должна быть запущена одновременно, конечно надо. А то они будут затирать правила друг друга в зависимости от того, кто последний запустился.

**Comment by Vascom** [comment]
Ну по умолчанию включен firewalld, так что указывать специально смысла нет.
В общем, мне кажется не стоит ничего менять, это же FAQ, а не глубокое исследование принципов firewall в федоре.

**Comment by xvitaly** [comment]
> Но явно ложные высказывания стоит исключить, мне кажется. Ведь во фразе говорится как раз о принципах работы.

Ждём pull request.

**Comment by xvitaly** [comment]
Merged.
