### ISSUE TITLE
Установка Microsoft Core Fonts в Fedora

### ISSUE THREAD

**Issue by sotnikov123** [RussianFedora/FAQ#50]
Подробно опишите своё предложение:
https://www.easycoding.org/2011/08/14/ustanovka-microsoft-core-fonts-v-fedora.html

По-умолчанию wget не качает файл, если папка не создана
или надо добавить перед скачиванием
mkdir -p ~/rpmbuild/SPECS
или качать с созданием папки
wget -P ~/rpmbuild/SPECS  http://corefonts.sourceforge.net/msttcorefonts-2.5-1.spec

**Comment by xvitaly** [comment]
Правильно будет так: `rpmdev-setuptree`. Обновил статью, спасибо.
