### ISSUE TITLE
Полезные сторонние репозитории для Fedora - 3

### ISSUE THREAD

**Issue by sotnikov123** [RussianFedora/FAQ#51]
Подробно опишите своё предложение:
https://www.easycoding.org/2017/03/24/poleznye-storonnie-repozitorii-dlya-fedora.html/

Раз уж факт отключения щупов подтвердить или опровергнуть не получается, 
можно добавить репу атома для выбора кому сливать свою телеметрию.
Тем более настройка атомовского репозитория также не содержит skip_if_unavailable=True

https://flight-manual.atom.io/getting-started/sections/installing-atom/#red-hat-and-centos-yum-or-fedora-dnf

**Comment by xvitaly** [comment]
По вопросу Atom даже не знаю ибо это настолько ужасный браузеро-редактор.

**Comment by xvitaly** [comment]
Добавлен.
