### ISSUE TITLE
Автоматически разблокируем LUKS диски при помощи TPM

### ISSUE THREAD

**Issue by XunSuslo** [RussianFedora/FAQ#67]
Страница, на которой присутствует ошибка: 
https://www.easycoding.org/2019/09/24/avtomaticheski-razblokiruem-luks-diski-pri-pomoshhi-tpm.html
Подробно опишите её:
В пункте "Проверка функциональности" допущена ошибка, из-за которой тестовая расшифровка происходит с ошибкой `JWE is missing the required 'clevis.pin' header property!`, а именно: вместо `cat test.jwe | clevis decrypt tpm2` используется `echo test.jwe | clevis decrypt tpm2` (на месте echo должен стоять cat)

**Comment by xvitaly** [comment]
Исправлено. Спасибо.
