### ISSUE TITLE
Опасное отключение модулей. Нужно дополнить инструкцию.

### ISSUE THREAD

**Issue by mecurc** [RussianFedora/FAQ#74]
**Страница, на которой присутствует ошибка:**
https://russianfedora.github.io/FAQ/package-manager.html#dnf-disable-modules

**Подробно опишите её:**
Эти команды безопасны только для систем в которых точно не устанавливались модульные пакеты. Если такие пакеты устанавливались, тогда нужно сначала удалить установленные из модулей пакеты, иначе они задовнгрейдятся/обновятся до актуальных версий из основных реп. Это опасная операция, т.к. версии из модулей обычно отличаются мажорной версией.

Фактически мы меняем модуль-стрим, а это рисковая и не очень поддерживаемя операция.
https://docs.fedoraproject.org/en-US/modularity/using-modules-switching-streams/

Я столкнулся с этим, когда использовал модули БД и интерпретаторов и чуть не поломал кучу всего.

**Что будет фиксом**
Я считаю, что нужно либо добавить варнинг, либо дополнить инструкцию командой, которая будет удалять установленные из модулей пакеты(пусть будет хотя бы менее опасной операцией).

**Comment by mecurc** [comment]
И хорошо бы добавить какой-то пруф, что модули депрекейтед. Не нашел это на вики федоры.

**Comment by mecurc** [comment]
Посмотреть список модульных пакетов

```bash
rpm --query --all --queryformat '%{name} %{modularitylabel}\n' \
  | grep --invert-match '(none)' \
  | cut --fields 1 --delimiter " "
```

Удалить модульные пакеты вместе с `fedora-repos-modular`
```bash
modular_packages_to_delete=`
rpm --query --all --queryformat '%{name} %{modularitylabel}\n' \
  | grep --invert-match '(none)' \
  | cut --fields 1 --delimiter " "
`
dnf remove $modular_packages_to_delete fedora-repos-modular
unset $modular_packages_to_delete
```

Я намеренно избежал сокращения флагов, чтобы сделать команду более доступной к пониманию.

**Comment by xvitaly** [comment]
1. Удалять ничего не требуется - `dnf module reset '*'` сбросит все модули до заводских настроек, уничтожив все привязанные контексты.
2. Команда `dnf distro-sync` после отключения модульного репозитория осуществит замену модулей до версий из репозитория ибо привязка была снята на первом этапе.
3. Исключительно модульные пакеты [запрещены FESCo](https://pagure.io/fesco/issue/2406), поэтому каждый мейнтейнер модульных версий обязан поддерживать также и обычный релиз в основном репозитории, поэтому отключение модульных репозиториев абсолютно безопасно.

**Comment by mecurc** [comment]
Да, спасибо за ссылочку, после прочтения стало намного понятнее.

Например я знал, что делает `dnf distro-sync`, но не думал что модульные пакеты будут обновлены до обычных из основного репа. Для моей конфигурации это было breaking change (сменилась версия постгреса).

**Comment by mecurc** [comment]
Странно, читаю политику с https://sgallagh.fedorapeople.org/docs/modularity/modularity/policies/, а там:

`
Packages MAY convert from a non-modular package to a modular default stream (or the reverse) only in Rawhide or during Fedora upgrades.
`

`upgrades` имеется в виду в рамках релиза или просто обновление? Если понимать это как в рамках обновления с версии на версию, то мы явно сталкиваемся с ошибкой. Если речь про простое обновление, то всё ок.

**Comment by xvitaly** [comment]
> Странно, читаю политику

Это всё устарело. Выше ссылка на FESCo. Модули без обычных пакетов запрещены в Fedora.

> upgrades имеется в виду в рамках релиза или просто обновление? Если понимать это как в рамках обновления с версии на версию, то мы явно сталкиваемся с ошибкой. Если речь про простое обновление, то всё ок.

Команда `dnf distro-sync` делает то же самое, что и обновление между релизами дистрибутива: все пакеты откатываются принудительно до версий из репозиториев. Как только модульные будут отключены, установится обычная версия из fedora или updates (в зависимости от того, что выше).

**Comment by mecurc** [comment]
Хорошо, тогда следующий вопрос, принципиально ли в каком порядке выполнять эти команды, если модульные пакеты могли быть установлены в системе?

```bash
  dnf remove fedora-repos-modular ${modular_packages}
  dnf module reset '*'
  dnf distro-sync
```

Или правильно будет так?

``` bash
  dnf module reset '*' 
  dnf remove fedora-repos-modular ${modular_packages}
  dnf distro-sync
```

В моих тестах это не принципиально, но я могу

**Comment by xvitaly** [comment]
> Хорошо, тогда следующий вопрос, принципиально ли в каком порядке выполнять эти команды, если модульные пакеты могли быть установлены в системе?

Сначала reset, затем удаление пакета с репозиториями и в конце distro-sync.
