### ISSUE TITLE
У меня 8 ГБ памяти. Нужен ли мне раздел подкачки?

### ISSUE THREAD

**Issue by hakavlad** [RussianFedora/FAQ#81]
Подробно опишите своё предложение:

>Для большинства сценариев использования на рабочих станциях 8 ГБ оперативной памяти будет вполне достаточно, поэтому раздел подкачки можно не создавать.

На самом деле подкачка крайне желательна практически при лоюбом размере оперативы.

См https://habr.com/ru/company/flant/blog/348324/  и  https://chrisdown.name/2018/01/02/in-defence-of-swap.html

Во-вторых, 8 гиг очень мало для того чтобы не иметь свопа. Может при 64 гиг нормально не иметь подкачку, но не при 8 гигах. 8 гиг один браузер может выжрать.

Предлагаю ссылку на статью также добавить туда.

И да, в современной федоре своп на zram создает мало тормозов, так что бояться особо нечего.

И без свопа хуже работает юзерспейсный киллер. А оомд без свопа вовсе не рабортает.

**Comment by xvitaly** [comment]
Речь шла о физическом swap на HDD. Я переформулирую вопрос. ZRAM работает по дефолту и он топ.
