### ISSUE TITLE
Неверный пакет для установки

### ISSUE THREAD

**Issue by ivan-tretyak** [RussianFedora/FAQ#92]
В вопросе измерения [скорости локальной или беспроводной сети](https://russianfedora.github.io/FAQ/networking.html#id4) указан неверный пакет для установки. Iperf2 отсутствует в репозиториях.

**Comment by Vascom** [comment]
Да, надо заменить на `iperf`

**Comment by xvitaly** [comment]
На iperf3. Но нужно проверить параметры командной строки.

**Comment by ivan-tretyak** [comment]
Проверил на iperf3 с ключами, указанными в FAQ для iperf2(iperf) работает.
